# Generated by Django 6.0.5 on 2026-10-02 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_code', models.TextField(blank=True, null=True)),
                ('category_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('donation_no', models.CharField(max_length=50, unique=True)),
                ('donation_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimated_unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('donor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('grn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grn_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('receipt_date', models.DateField()),
                ('received_by', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('received_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods_receipt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('item_id', models.BigAutoField(db_column='Item_id', primary_key=True, serialize=False)),
                ('item_name', models.TextField(db_column='Item_name')),
                ('item_description', models.TextField(blank=True, db_column='Item_description', null=True)),
                ('item_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('unit_id', models.BigIntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_stock', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('reorder_level', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('maximum_stock', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('is_perishable', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.TextField()),
            ],
            options={
                'db_table': 'item_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proc_date', models.DateField(blank=True, null=True)),
                ('po_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('unit_price', models.FloatField()),
                ('details', models.CharField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('shed_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shed_name', models.TextField()),
            ],
            options={
                'db_table': 'shed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('quantity', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('unit', models.TextField()),
                ('stock_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_id', models.BigIntegerField(blank=True, null=True)),
                ('bin_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, max_length=20, null=True)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('transection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_warehouse', models.BigIntegerField()),
                ('to_warehouse', models.BigIntegerField()),
                ('quantity', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('issue_date', models.DateField()),
                ('reciving_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('image_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('st_loc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'storage_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageShed',
            fields=[
                ('sto_shed_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'storage_shed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StorageType',
            fields=[
                ('type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.TextField()),
            ],
            options={
                'db_table': 'storage_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ntn', models.CharField(blank=True, max_length=50, null=True)),
                ('gst', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=50)),
                ('unit_symbol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('master', 'Master'), ('location', 'Location user')], default='location', max_length=20)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='db.locations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
