# Generated by Django 6.0.5 on 2026-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_goods_receipt_line_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('location', 'Storage location user')], default='location', max_length=20),
        ),
    ]
