# Generated by Django 6.0.5 on 2026-10-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_userprofile_role_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('master', 'Master'), ('all_areas', 'All areas user'), ('location', 'Storage location user')], default='location', max_length=20),
        ),
    ]
